spring.application.name=Ecommerce

#for change the server
server.port=${PORT:8080}

spring.datasource.url=jdbc:mysql://localhost:3306/CartiFy
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:Golu@1234}

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=cartifyofficials@gmail.com
spring.mail.password=fvyv llmg vlfz lktd
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#New 

# spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:ecommerce_multi_vendor}


#ORM s/w specific properties
stripe.api.key=sk_test_123456
razorpay.api.key=rzp_test_We2TfD6XCCwnVb
razorpay.api.secret=HCf5zET87ehk5fkEGi0l3wj5


spring.devtools.livereload.enabled=true

#ai
gemini.api.key=AIzaSyBcNyVPoGK4aT3edD2cqW8XhKdtvKA7MUc
